import Header from "@/components/layout/Header";
import Sidebar from "@/components/layout/Sidebar";
import { Geist, Geist_Mono } from "next/font/google";
import { Metadata } from "next";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex">
          {/* Sidebar */}
          <Sidebar />

          {/* Main Section */}
          <div className="flex-1 min-h-screen">
            <Header />

            <main className="p-4">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
